version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sifat-smk-hijaumuda
    container_name: sifat_app
    restart: always
    ports:
      - "8000:10000"
    environment:
      - PORT=10000
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=sifat_db
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - sifat-network

  db:
    image: mysql:8.0
    container_name: sifat_db
    restart: always
    environment:
      MYSQL_DATABASE: sifat_db
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sifat-network

volumes:
  db_data:

networks:
  sifat-network:
    driver: bridge